export const BLOG_ACTIONS = {
  INIT: 'INIT',
  NEW_BLOG: 'NEW_BLOG',
  REMOVE_BLOG: 'REMOVE_BLOG',
  ADD_LIKE: 'ADD_LIKE',
}

export const NOTIFICATION_ACTIONS = {
  SET_NOTIFICATION: 'SET_NOTIFICATION',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION'
}

export const USER_ACTIONS = {
  LOGIN: 'LOGIN',
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT'
}